### ISSUE TITLE
add 9.9.15 version

### ISSUE THREAD

**Issue by auto-amc** [ege2097yilmaz/Carla-simulator-projects#1]
Please add version 0.9.9.15.
Thank you

**Comment by bahademircioglu** [comment]
Hello,

If you're referring to version 0.9.15, both the simulator/dockerfile and carlAPI/dockerfile files are already set to use Carla 0.9.15 via the line:
"
FROM carlasim/carla:0.9.15
"
However, if you mean a different version (e.g., 0.9.9.15), we are unaware of any Carla release by that name. Could you please provide a URL or additional details about this specific version? This will help us understand the issue better.

If no further information is provided, we will close this issue in 3 days.

You may also adjust the version in the Dockerfiles if needed...

Updated the readme in docs to container installation.

Kind regards,
Baha

**Comment by ege2097yilmaz** [comment]
Hello, 

You may change the version of the Carla in dockerfiles as you wish. These dockerfiles are based on Carla 9.15 version. And other files are working with this version. Note that, python carla library version must match with your carla simulator version

Best Regards
Ege
